databases:
  - name: FairBNB
    databaseName: FairBNB
    user: FairBNB

services:
  - type: web
    name: FairBNB
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: FairBNB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
